#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 128		# Set DPI. User may want to use a larger number for larger screens. 96 128 192
xrandr --output DP-3 --mode 2560x1440 --rate 240 --left-of DP-2;
sleep 0.1;
xrandr --output DP-2 --mode 2560x1440 --rate 240 --primary;
sleep 0.1;
xrandr --output HDMI-1 --mode 1920x1080 --rate 60 --left-of DP-3 --reflect normal

setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup DO NOT FUCKING UNCOMMENT THIS!!!!!!!!!!!!!!!!!!! 
xset r rate 300 50 &	# Speed xrate up
xset s off -dpms

autostart="mpd xcompmgr dunst unclutter pipewire remapd numlockx"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
	sleep 0.01
done >/dev/null 2>&1

yams -d -t 10 >/dev/null 2>&1

LD_LIBRARY_PATH=/usr/lib/pentablet/lib /usr/lib/pentablet/PenTablet.sh >/dev/null 2>&1 &
sleep 2 && xlsw | grep 'Pentablet' | awk '{print $1}' | while read _windowID; do xdotool windowclose "${_windowID}"; done

wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%- && wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+; kill -44 $(pidof dwmblocks)
wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%+ && wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-; kill -44 $(pidof dwmblocks)

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
