#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
xset r rate 300 50 &	# Speed xrate up
setxkbmap us intl

autostart="mpd xcompmgr dunst unclutter pipewire remapd yams numlockx"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
        sleep 0.01
done >/dev/null 2>&1

LD_LIBRARY_PATH=/usr/lib/pentablet/lib /usr/lib/pentablet/PenTablet.sh >/dev/null 2>&1 &
sleep 2 && xlsw | grep 'Pentablet' | awk '{print $1}' | while read _windowID; do xdotool windowclose "${_windowID}"; done

wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%- && wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+; kill -44 $(pidof dwmblocks)
wpctl set-volume @DEFAULT_AUDIO_SINK@ 0%+ && wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-; kill -44 $(pidof dwmblocks)

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
